version: 1

before:
  hooks:
    - go mod tidy

builds:
  - id: "mobius-hotline-server"
    main: ./cmd/mobius-hotline-server
    binary: mobius-hotline-server
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
      - arm
    goos:
      - linux
      - windows
      - darwin
#  - id: "mobius-hotline-client"
#    main: ./cmd/mobius-hotline-client
#    binary: mobius-hotline-client
#    env:
#      - CGO_ENABLED=0
#    goarch:
#      - amd64
#      - arm64
#    goos:
#      - linux
#      - windows
#      - darwin

archives:
  - id: "mobius-hotline-server"
    format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_server_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
#  - id: "mobius-hotline-client"
#    format: tar.gz
#    # this name template makes the OS and Arch compatible with the results of `uname`.
#    name_template: >-
#      {{ .ProjectName }}_client_
#      {{- title .Os }}_
#      {{- if eq .Arch "amd64" }}x86_64
#      {{- else if eq .Arch "386" }}i386
#      {{- else }}{{ .Arch }}{{ end }}
#      {{- if .Arm }}v{{ .Arm }}{{ end }}
#    # use zip for windows archives
#    format_overrides:
#      - goos: windows
#        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
